import { config } from "../../config.js";
import { anthropicProvider } from "./providers/anthropic.js";
import { openaiProvider } from "./providers/openai.js";
import { routeLLMRequestByDay } from "./batchPlanner.js";
import { buildSystemPrompt, buildUserMessage } from "./promptBuilder.js";
import { parseAndValidateLLMOutput, LLMOutputParseError } from "./outputParser.js";
import type { LLMPlannerInput, LLMScheduleOutput } from "@shiftagent/shared";
import type { LLMProvider, LLMRawResult } from "./types.js";
import { query } from "../../db/pool.js";

const MAX_ATTEMPTS = 2;

function getProvider(): LLMProvider | null {
  if (config.llmProvider === "openai") {
    return openaiProvider.isConfigured() ? openaiProvider : null;
  }
  return anthropicProvider.isConfigured() ? anthropicProvider : null;
}

function emptyOutput(reason: string): LLMScheduleOutput {
  return {
    shifts: [],
    unfilled_slots: [],
    summary: "Schedule generated by the rule-based engine (AI suggestion unavailable this run).",
    warnings: [reason],
  };
}

async function logGeneration(params: {
  scheduleId: string;
  workplaceId: string;
  result: LLMRawResult;
  violationsFixed?: number;
}): Promise<void> {
  try {
    await query(
      `INSERT INTO llm_generation_log
       (schedule_id, workplace_id, model_used, provider_name, prompt_tokens, completion_tokens,
        generation_time_ms, validation_attempts, hard_constraint_violations_fixed)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [
        params.scheduleId,
        params.workplaceId,
        params.result.model,
        params.result.providerName,
        params.result.promptTokens,
        params.result.completionTokens,
        params.result.generationTimeMs,
        params.result.attempt,
        params.violationsFixed ?? 0,
      ]
    );
  } catch (err) {
    console.warn("[LLMRouter] Failed to write llm_generation_log:", err);
  }
}

/**
 * Routes LLM requests to the configured provider. Attempt 1 uses the fast/cheap
 * model; attempt 2 escalates to the quality model (Anthropic only). Never throws.
 */
export async function routeLLMRequest(
  input: LLMPlannerInput,
  scheduleId: string
): Promise<LLMScheduleOutput> {
  const provider = getProvider();
  if (!provider) {
    return emptyOutput("AI scheduling key not configured. Schedule generated from rules only.");
  }

  if (input.employees.length >= config.llmBatchMinEmployees) {
    console.log(
      `[LLMRouter] Batching by day (${input.employees.length} employees, threshold ${config.llmBatchMinEmployees})`
    );
    return routeLLMRequestByDay(input, scheduleId, provider, (result) =>
      logGeneration({ scheduleId, workplaceId: input.workplace_id, result })
    );
  }

  const systemPrompt = buildSystemPrompt();
  const userMessage = buildUserMessage(input);
  let lastError: LLMOutputParseError | null = null;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const result = await provider.generate({ systemPrompt, userMessage, attempt });
      await logGeneration({ scheduleId, workplaceId: input.workplace_id, result });

      try {
        return parseAndValidateLLMOutput(result.rawOutput);
      } catch (err) {
        if (err instanceof LLMOutputParseError) {
          lastError = err;
          const preview = err.rawOutput.slice(0, 400).replace(/\s+/g, " ");
          if (config.nodeEnv !== "production") {
            console.warn(
              `[LLMRouter] Attempt ${attempt} failed validation: ${err.message}` +
                (preview ? ` | raw: ${preview}${err.rawOutput.length > 400 ? "…" : ""}` : "")
            );
          } else {
            console.warn(`[LLMRouter] Attempt ${attempt} failed validation: ${err.message}`);
          }
          continue;
        }
        throw err;
      }
    } catch (err) {
      if (err instanceof LLMOutputParseError) {
        lastError = err;
        continue;
      }
      console.error("[LLMRouter] Provider API error, falling back to rules:", err);
      return emptyOutput("AI scheduling was unavailable. Schedule generated from rules only.");
    }
  }

  console.error("[LLMRouter] All attempts failed:", lastError?.message);
  return emptyOutput("AI scheduling output could not be validated. Schedule generated from rules only.");
}

export function isLLMConfigured(): boolean {
  return getProvider() !== null;
}
